### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ipycache-feedstock#1]
License should be update w.r.t. to the resolution of this issue ( https://github.com/rossant/ipycache/issues/41 ). Though the included license file appears to be a verbatim BSD 3-Clause license. Maybe you could help clarify the cause of confusion, @jochym.

Edit: Note this issue is a follow-up on this [discussion](https://github.com/conda-forge/staged-recipes/pull/569/files/e9197e380d5773b31ee9b803b219a1d0fc0003e9#diff-0b037187e74e019fad42e0a181f7b0d3R43) at staged-recipes.

**Comment by jochym** [comment]
It is indeed BSD-3 as far as I know. I do not think there is any point to keep this issue open.

**Comment by jakirkham** [comment]
The reason this is open is the [recipe](https://github.com/conda-forge/ipycache-feedstock/blob/eae07b4cd9e89398c126b6b4154d242d41106f09/recipe/meta.yaml#L47) needs to be updated. If it is BSD 3-Clause, could you please update it? Also please [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy` version `1.3.3` when doing this.

**Comment by jakirkham** [comment]
Addressed in commit ( https://github.com/conda-forge/ipycache-feedstock/commit/386dc3a55dea0a23fa00921c5343c5d0660e2bd1 ) and since re-rendered.
